import json, glob
N={json.load(open(f))['case']: json.load(open(f)) for f in glob.glob('results/v2/necessity/case*.json')}
order=['case1_three_techniques','case2_annotated','case3_contradicts','case4_oracle','case5_drop']
P=print
P("# Measured necessity by removal")
P("")
P("**Every verdict is model against model.** Necessity here is not a property of a panel: it is a")
P("measurement relative to **this answerer, this prompt and this model**, and would move with any of them.")
P("**No item in this pipeline has been checked by a person**, and the 21-page audit pack from the previous")
P("run (`results/v2/audit_pack/`) is still unread.")
P("")
P("## 1. The answerer and the protocol")
P("")
P("| | |")
P("|---|---|")
P("| answerer | `net-claim`, `model: sonnet`, `tools: Read` only |")
P("| input | claim text, the paper's setup context, panel images. No observation text, no contribution label, no step structure; machine-checked before every dispatch |")
P("| verdicts | supported / partly supported / cannot tell / contradicted, with a confidence 0-1 |")
P("| threshold | `drop > 0.15`, **fixed in advance** |")
P("| repeats | 3 per configuration; majority verdict, median confidence |")
P("| necessity | removal **strictly weakens** the verdict from wherever the full run started, or `drop` clears the threshold |")
P("| calls | 168: per case one full run, one per panel, one per channel, one no-panel floor, x3 |")
P("")
P("## 2. Per case, both granularities")
P("")
P("| case | full run | floor (no panels) | panel-level | channel-level |")
P("|---|---|---|---|---|")
for k in order:
    o=N[k]
    P(f"| {k} | {o['full_verdict']} {o['full_confidence']} | {o['confidence_floor']['verdict']} {o['confidence_floor']['confidence']} | "
      f"{o['n_necessary']}/{o['n_panels']} **{o['split']}** | {o['n_necessary_channels']}/{o['n_channels']} **{o['channel_split']}** |")
P("")
P("Case 1 has one panel per channel, so its channel column is the same measurement twice, not a second one.")
P("")
P("### Channel-level removal, which is what this part existed to test")
P("")
P("| case | channel | panels | verdict without it | drop | rank | necessary |")
P("|---|---|---|---|---|---|---|")
for k in order:
    for c in sorted(N[k]['channels'], key=lambda x: (x['drop'] is None, -(x['drop'] or 0))):
        P(f"| {k} | {c['channel']} | {c['n_panels']} | {c['verdict_without']} | {c['drop']} | {c['rank']}{' (tie)' if c.get('tied') else ''} | {'**yes**' if c['necessary'] else 'no'} |")
P("")
P("**Case 4 is the win.** Panel-level read 0 of 6, all-redundant: pull any one XAS panel and the other three")
P("carry it. Pull the whole XAS channel and the verdict falls to `cannot tell`, drop -0.30. Channel-level")
P("turned an all-redundant chain into a mixed one, which is the hypothesis this part was built to test.")
P("")
P("**Case 5 did not move.** 16 panels in three channels of 6, 4 and 6; removing any whole channel still")
P("leaves `partly supported` at the same confidence. Per the stop rule this is a property of the chain")
P("rather than a failure of the method: **a chain of roughly five panels or more cannot be discriminated by")
P("removal at any granularity**, because whatever remains still carries the claim.")
P("")
P("**Case 2 moved the wrong way**, mixed at panel level and all-redundant at channel level. The reason")
P("matters more than the result; see section 4.")
P("")
P("## 3. Discrimination, and the floor")
P("")
P("- **Mixed splits: 3 of 5 at panel level, 3 of 5 at channel level, but not the same three.** Either")
P("  granularity alone gives 3/5; counting a chain as discriminated when *either* separates it gives")
P("  **4 of 5**, with only case 5 constant under both.")
P("- **Repeat instability: 0 of 56 configurations** disagreed across three repeats; the stop rule was one")
P("  third. The measurement is deterministic here, which is why a 0.05 drop is signal rather than noise,")
P("  and also why the confidences are visibly quantised.")
P("- **The confidence floor says `cannot tell` on all five, never `supported`.** The claims are not")
P("  self-persuasive from text and setup alone. This is the first of the three metrics tried in this run to")
P("  clear that bar, and it is the precondition for any evidence metric meaning anything.")
P("")
P("## 4. What the numbers say about the metric itself")
P("")
P("**`drop` is conditional on the verdict, so most drops are not comparable.** The answerer reports")
P("confidence *in the verdict it gave*. A full run at `partly supported` 0.45 against a removal run at")
P("`cannot tell` 0.95 differs by -0.50, but that is not a gain in support: it is high confidence in a")
P("weaker answer. 4 of 46 drops span a changed verdict and are meaningless; every negative drop in the")
P("tables above is that artefact. Only the **42 drops where the verdict held** are interpretable.")
P("")
P("**Removal is non-monotonic in one case.** In case 2, removing panel F4b alone gives `cannot tell`, while")
P("removing the whole TEM channel, F4a **and** F4b, gives `partly supported`. Removing strictly more")
P("evidence produced a strictly stronger verdict. With 0% repeat variance that is not noise; it is the")
P("answerer reacting to what remains rather than to what was taken. It bounds how much weight one removal")
P("can carry, and it is why case 2 flips split between granularities.")
P("")
P("**The ordering is real but shallow.** Repeat spread is 0.0, so any non-zero drop clears it and every")
P("case reports `ordering_outside_noise = true`. But the drops sit at 0.0 and +/-0.05 with two exceptions:")
P("case 1 XRD at 0.20 and case 4 XAS at -0.30. Case 5's three channels tie at exactly 0.0, so it has no")
P("ordering and the table says rank 1 (tie) three times rather than inventing 1, 2, 3.")
P("")
P("## 5. Against the labels we already had")
P("")
P("34 panel rows across the five cases.")
P("")
P("| comparison | agreement |")
P("|---|---|")
P("| measured (panel) vs **structural leave-one-out, free from the graph** | **5/34 = 15%** |")
P("| measured (panel) vs measured (channel) | 27/34 = 79% |")
P("")
P("**The free structural version is not a usable proxy, and the reason disqualifies it outright.** It calls")
P("32 of 34 panels `necessary` where the measurement calls 31 `redundant`. Worse, it is an artefact of")
P("whichever label feeds it: computed over `image_support` it called most channels")
P("`redundant_by_single_loo`; recomputed, rule unchanged, over `contribution`, where nearly every step is")
P("`partial`, it calls almost everything `necessary`. Only the upstream label moved. A proxy that inverts")
P("when you swap the label beneath it is measuring the label, not the evidence.")
P("")
P("So the expensive measurement is **not** merely calibration for a free one. There is no free one.")
P("")
P("## 6. Recommendation")
P("")
P("**Measured necessity is usable for support chains, under three conditions.**")
P("")
P("1. **Use the verdict flip, not the drop.** The flip carried every genuine result here: case 3's PL")
P("   channel, case 4's XAS channel, case 1's XRD panel. The drop is quantised, conditional on the verdict,")
P("   and uninterpretable exactly when the verdict moves, which is when it matters.")
P("2. **Remove at channel level**, keeping panel level as a cross-check. Channel removal rescued case 4;")
P("   panel removal inside a four-panel channel measures redundancy and nothing else.")
P("3. **Cap chains at about five panels.** Case 5, at 16, is constant under both granularities. Above that")
P("   size no removal discriminates, so the chain is cut down or it is not gradeable this way.")
P("")
P("Against the two metrics this run discarded, that is a real improvement: `image_support` answered a")
P("different question than the chain asked, `contribution` was a sound label that came back 90% constant on")
P("multi-evidence claims, and this one has a working floor, deterministic repeats, and separates 4 of 5")
P("chains under one granularity or the other. It is also the only one of the three whose ground truth is an")
P("experiment rather than another model's opinion, though the experiment is still run by a model.")
P("")
P("**What would settle it:** the audit pack. 21 pages, one per step, unread. Everything above is models")
P("checking models.")
P("")
P("## Files")
P("")
P("- `results/v2/necessity/<case>.json` - full run, per-panel and per-channel rows, floor, ranks, splits")
P("- `results/v2/necessity/agreement.json` - the 34-row comparison behind section 5")
P("- `.claude/agents/net-claim.md` - the answerer")
P("- `trace_kit_v2/necessity.py` - configurations, guard, collection")
P("")
P("Every verdict is model against model.")
